services:
  whoami:
    image: "traefik/whoami"
    container_name: "dev-simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.prod.erasmusbot.cz`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
    networks:
      - "traefik_network"
  streamlit:
    image: "essare164/streamlit-gerrit"
    container_name: "dev-streamlit"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit.rule=Host(`streamlit.prod.erasmusbot.cz`)"
      - "traefik.http.routers.streamlit.entrypoints=websecure"
      - "traefik.http.routers.streamlit.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
    networks:
      - "traefik_network"
  fastapi:
    image: "essare164/fastapi-gerrit"
    container_name: "dev-fastapi-gerrit"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.prod.erasmusbot.cz`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
    networks:
      - "traefik_network"