services:
  dev_whoami:
    image: "traefik/whoami"
    container_name: "dev-simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev_whoami.rule=Host(`whoami.dev.erasmusbot.cz`)"
      - "traefik.http.routers.dev_whoami.entrypoints=websecure"
      - "traefik.http.routers.dev_whoami.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=3"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=3"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.period=1m"
      - "traefik.http.routers.dev_whoami.middlewares=test-ratelimit"

    networks:
      - "traefik_network"
  dev_streamlit:
    image: "essare164/streamlit-gerrit"
    container_name: "dev-streamlit"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev_streamlit.rule=Host(`streamlit.dev.erasmusbot.cz`)"
      - "traefik.http.routers.dev_streamlit.entrypoints=websecure"
      - "traefik.http.routers.dev_streamlit.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
    networks:
      - "traefik_network"
  dev_fastapi:
    image: "essare164/fastapi-gerrit"
    container_name: "dev-fastapi-gerrit"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.dev.erasmusbot.cz`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - "traefik.docker.network=root_traefik_network"
    networks:
      - "traefik_network"