---
- name: Deploy to droplet
  hosts: droplet
  tasks:
    - name: Config containers
      tags: config
      block:
        - name: Template docker_compose.yml.j2
          ansible.builtin.template:
            src: templates/docker-compose.yml.j2
            dest: '{{ checkout_path }}/docker-compose.yml'
    - name: Deploy containers
      tags: deploy
      block:
        - name: run docker compose
          ansible.builtin.shell: docker compose up -d
          args:
            chdir: '{{ checkout_path }}'