---
# make another step which would be build & push
name: Build & Push containers
run-name: Building & Pushing containers
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./fast_api
          push: true
          tags: essare164/fastapi-gerrit:latest

name: Deploy containers
run-name: Deploying containers
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Run playbook
      - uses: actions/checkout@v3
        env:
          DROPLET_IP: ${{ vars.DROPLET_IP }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_SECRET: ${{ secrets.FACEBOOK_SECRET }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy/main.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, additional flags to pass to ansible-playbook
          options: |-
            --inventory deploy/hosts.yml
            --extra-vars @deploy/defaults/main.yml 
            --verbose